# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: bookshop_db_mysql
    command:  mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'--innodb-flush-log-at-trx-commit=0 --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'Gun1234'
      MYSQL_DATABASE: 'my_project'
    volumes:
      - ./my_bookshop_db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

      
